# Generated by Django 4.2.1 on 2023-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='is_moderator'),
        ),
    ]
