# Generated by Django 4.2.1 on 2023-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(choices=[('no', 'no'), ('CHUI', 'CHUI'), ('DJALAL-ABAD', 'DJALAL-ABAD'), ('OSH', 'OSH'), ('NARYN', 'NARYN'), ('TALAS', 'TALAS'), ('ISSYK-KUL', 'ISSYK-KUL')], max_length=120),
        ),
    ]
