# Generated by Django 4.2.2 on 2023-06-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_delete_nation_alter_agent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='property',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
