# Generated by Django 4.2.2 on 2023-06-17 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_alter_advertisement_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='feedback',
            field=models.ManyToManyField(blank=True, default=None, to='property.feedback'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishlist_advertisement', to=settings.AUTH_USER_MODEL),
        ),
    ]
