# Generated by Django 4.2.1 on 2023-06-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='property.feedback'),
        ),
    ]
