# Generated by Django 4.2.1 on 2023-06-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_feedback_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='property',
            name='featrued',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('Year', 'Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years')], max_length=300, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_advertisement', to='property.property'),
            preserve_default=False,
        ),
    ]
