# Generated by Django 4.2.2 on 2023-06-17 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_remove_property_duration_remove_property_featrued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_advertisement', to=settings.AUTH_USER_MODEL),
        ),
    ]
